version: '2'
services:
  nodeserver:
    build: ./containers/node
    volumes:
      - .:/code
    environment:
      - NODE_PATH=./server/core
    depends_on:
      - mongodb
  webserver:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
          - nodeserver
  mongodb:
    image: mongo
    ports:
      - "27017:27017"